#!/bin/bash

INSTALL_DIR=/usr/arm-tinyos
FINAL_INSTALL_DIR=`pwd`/packages/
TARGET=arm-none-eabi			# Target platform
PREFIX=${INSTALL_DIR}   		# Install location of your final toolchain
PARALLEL=-j`getconf _NPROCESSORS_ONLN`	# Parallel build options

TOSOPENOCD=openocd-0.5-rc2

MAIN_DIR=$(pwd)
SOURCES=${MAIN_DIR}/sources

if [ ! -e ${SOURCES} ]; then
    mkdir ${SOURCES}
fi

cd ${SOURCES}

echo "Downloading openocd repository..."
git clone -b v0.5.0-rc2	git://openocd.git.sourceforge.net/gitroot/openocd/openocd $TOSOPENOCD
tar cvfz ${TOSOPENOCD}.tar.gz ${TOSOPENOCD}

cd ${MAIN_DIR}

if [ ! -e build ]; then
    mkdir build
fi

if [ ! -e .openocd.build ]; then
    tar xvfz ${SOURCES}/${TOSOPENOCD}.tar.gz

    pwd
    cd ${TOSOPENOCD}/
    #patch -p0 < ../openocd.patch
    ./bootstrap || exit
    cd -
    cd build
    ../${TOSOPENOCD}/configure --prefix=${FINAL_INSTALL_DIR}/${TOSOPENOCD}/${PREFIX} \
			  --enable-maintainer-mode \
                          --enable-ft2232_libftdi                         \
                          --enable-jlink \
                          || exit
    make ${PARALLEL} || exit
    ../${TOSOPENOCD}/configure --prefix=${FINAL_INSTALL_DIR}/${TOSOPENOCD}/${PREFIX} \
                          --enable-ft2232_libftdi                         \
                          --enable-jlink \
                          || exit
    make ${PARALLEL} || exit
    make install || exit

    touch .openocd.build
    rm -rf build/* 
    rm -rf ${TOSOPENOCD}
fi
